# -*- coding: utf-8 -*-
"""UTS_SAADATUL_HAYATI_NUFUS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ru-6heYsjiS1b-krmzuU0cF95tnfZxFY?usp=sharing
"""
  
# Install library yang dibutuhkan
pip install -q google-play-scraper transformers torch pandas matplotlib seaborn

# Import library
from google_play_scraper import reviews, Sort
import pandas as pd
import csv
from transformers import pipeline
import matplotlib.pyplot as plt
import seaborn as sns

# ==============================
# 1. SCRAPING ULASAN INFO BMKG
# ==============================

result, _ = reviews(
    'com.Info_BMKG',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=100,
    filter_score_with=None
)

filename = 'ulasan_info_bmkg.csv'

with open(filename, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=['userName', 'score', 'at', 'content'])
    writer.writeheader()

    for review in result:
        writer.writerow({
            'userName': review.get('userName', ''),
            'score': review.get('score', ''),
            'at': review.get('at', ''),
            'content': review.get('content', '')
        })

print(f"Berhasil menyimpan {len(result)} ulasan ke '{filename}'")


# ==============================
# 2. MEMBACA DATA ULASAN
# ==============================

df = pd.read_csv('ulasan_info_bmkg.csv')

print("Data berhasil dimuat. Berikut 5 data pertama:")
display(df.head())


# ==============================
# 3. ANALISIS SENTIMEN ROBERTA
# ==============================

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="w11wo/indonesian-roberta-base-sentiment-classifier"
)

def get_sentiment(text):
    if pd.isna(text) or str(text).strip() == '':
        return {'label': 'neutral', 'score': 0.0}

    try:
        result = sentiment_pipeline(str(text), truncation=True)[0]
        return result
    except Exception as e:
        print(f"Error memproses teks: {str(text)[:50]}... Error: {e}")
        return {'label': 'error', 'score': 0.0}

df['sentiment_analysis'] = df['content'].apply(get_sentiment)

df['sentiment_label'] = df['sentiment_analysis'].apply(lambda x: x['label'])
df['sentiment_score'] = df['sentiment_analysis'].apply(lambda x: x['score'])

print("Analisis sentimen selesai. Berikut 5 data pertama:")
display(df.head())


# ==============================
# 4. DISTRIBUSI SENTIMEN
# ==============================

print("Distribusi Sentimen:")
print(df['sentiment_label'].value_counts())


# ==============================
# 5. VISUALISASI SENTIMEN
# ==============================

plt.figure(figsize=(8, 6))

sns.countplot(
    x='sentiment_label',
    data=df,
    hue='sentiment_label',
    palette='viridis',
    legend=False
)

plt.title('Distribusi Sentimen Ulasan Aplikasi Info BMKG')
plt.xlabel('Sentimen')
plt.ylabel('Jumlah Ulasan')
plt.show()


# ==============================
# 6. SIMPAN HASIL AKHIR
# ==============================

df.to_csv('hasil_sentimen_info_bmkg.csv', index=False, encoding='utf-8-sig')

print("Hasil analisis sentimen berhasil disimpan ke 'hasil_sentimen_info_bmkg.csv'")